name: Build CA

on:
  push:
    paths:
      - build.yaml

permissions:
  contents: read
  id-token: write  # This is needed for OIDC federation.

jobs:
  build-ca-image:
    runs-on: ubuntu-latest

    steps:
      - name: authenticate to chainguard
        uses: chainguard-dev/setup-chainctl@main
        with:
          identity: ${{ secrets.CHAINGUARD_IDENTITY }}

      - name: Check out repository
        uses: actions/checkout@v4
     
      - name: build-image-with-new-packages
        run: |
          yes | chainctl image repo build edit --parent jimmy.ungerman --repo go --save-as go-${{ github.event.repository.name }}-base -f build.yaml
      
      - name: Wait for new CA image to be available
        timeout-minutes: 10
        run: |
          while ! chainctl image repo list --parent jimmy.ungerman | grep go-${{ github.event.repository.name }}-base; do
            echo "Waiting for image to be available..."
            sleep 15
          done