name: Build CA

on:
  push:
    paths:
      - build.yaml
      
permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

env:
  BASE_IMAGE_NAME: go-${{ github.event.repository.name }}-base
  GO_VERSION: "1.25"

jobs:
  build-base-image:
    runs-on: ubuntu-latest

    steps:
      - name: authenticate to chainguard
        uses: chainguard-dev/setup-chainctl@main
        with:
          identity: ${{ secrets.CHAINGUARD_IDENTITY }}

      - name: Check out repository
        uses: actions/checkout@v4
     
      - name: build-base-image-with-new-packages
        run: |

          # Check if image exists
          if [[ $(chainctl image repo list --parent jimmy.ungerman --repo ${{ env.BASE_IMAGE_NAME}}) ]]; then

            # Apply new build.yaml and check if changes are going to be made
            if chainctl image repo build apply --parent jimmy.ungerman --repo ${{ env.BASE_IMAGE_NAME}} -f build.yaml | grep -q "No changes detected"; then
              echo "No changes to base image detected"
            else

              echo "Updating ${{ env.BASE_IMAGE_NAME}} with packages from build.yaml..."

              # Get digest of existing image tag
              pre_build_digest=$(chainctl image tag list --parent jimmy.ungerman --repo go-actions-ca-base -o json | jq -r --arg VERSION "${{ env.GO_VERSION }}" '.[] | select(.name == $VERSION) | .digest')

              # Apply new image config
              chainctl image repo build apply --parent jimmy.ungerman --repo ${{ env.BASE_IMAGE_NAME}} -f build.yaml -y > /dev/null

              # Check until the digest changes
              while true; do
                current_digest=$(chainctl image tag list --parent jimmy.ungerman --repo go-actions-ca-base -o json | jq -r --arg VERSION "${{ env.GO_VERSION }}" '.[] | select(.name == $VERSION) | .digest')
                if [[ "$pre_build_digest" != "$current_digest" ]]; then
                  echo "New base image built"
                  break
                else
                  echo "Building new base image..."
                fi

                sleep 20
              done
            fi
          
          else
            echo "Building new base image ${{ env.BASE_IMAGE_NAME}}"

            yes | chainctl image repo build edit --parent jimmy.ungerman --repo go --save-as ${{ env.BASE_IMAGE_NAME }} -f build.yaml > /dev/null

            while ! chainctl image tags list --parent jimmy.ungerman --repo ${{ env.BASE_IMAGE_NAME}} > /dev/null; do
              echo "Waiting for image tags to be available..."
              sleep 15
            done
          fi